### PR TITLE
Fixed Error in APTCodeModelHelper #1952

### PR DESCRIPTION
**Pull request by smaugho**

### CODE REVIEW

**Comment by WonderCsabo** [comment]
Can you change the commit message to be more specific?

**Comment by smaugho** [comment]
Do I remove the previous one?? Or is it enough just like this: 

dae5ba5faba148fb9c69bbde40478596

**Comment by WonderCsabo** [comment]
@smaugho do not remove the previous line, just add the new, like [this](https://github.com/androidannotations/androidannotations/blob/055177e7f52f1cedb080e3bd1f20d9522fea79fd/AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/efragment/MySupportFragment.java#L3).
Also, just write *2016* for now, we will update to *2016-2017* in a PR later. Thanks!

**Comment by smaugho** [comment]
Got it!

**Comment by smaugho** [comment]
new copyright added ;)

**Comment by dodgex** [comment]
Damn you github... @smaugho could you please rebase this PR to get rid of the `Merge branch 'develop' into 1952_error_in_aptcodemodelhelper` commit? I accidently clicked the "Udpate branch" button that automatically creates this merge... :(

Thank you! :)

**Comment by WonderCsabo** [comment]
@smaugho sorry for our mistake, can you address https://github.com/androidannotations/androidannotations/pull/1953#issuecomment-281092880 ?

**Comment by smaugho** [comment]
Hi sorry for the delay... I remade it (updated commit description)... does it help?..

**Comment by WonderCsabo** [comment]
@smaugho nope, you have to do the following:

```sh
git remote add upstream git@github.com:androidannotations/androidannotations.git
git fetch upstream
git rebase upstream/develop
```

This way your branch will become up-to-date with the base branch. Thanks!

**Comment by smaugho** [comment]
Done!

**Pull request merged**
