### PR TITLE
Use correct block for method injection of ViewById and ViewsById

### PR DESCRIPTION
**Pull request by dodgex**
fix https://github.com/androidannotations/androidannotations/issues/1966

### CODE REVIEW

**Comment by WonderCsabo** [comment]
@dodgex i do not understand this. The current code is using the injection block, and these are injection annotations.

**Comment by dodgex** [comment]
There is an issue with the order of injections. If you use method injection for a list of views there is a chance that you get an empty or only partially filled list in the injecting method. With this change the method injection is ensured to be called after all views have been resolved. you can see an example of generated code in the issue #1966

**Comment by WonderCsabo** [comment]
@dodgex but with your change, the view injections end up in the same block as `@AfterViews`. And in that case, in case of wrong handler order, `@AfterViews` generated code could be added before the view injections... We created the blocks to add code in correct order, and this change would revert that, making the blocks redundant.

**Comment by dodgex** [comment]
Oh damn... yeah. I forgot about `@AfterViews`. I'll see if i can find a better solution. :)

**Comment by dodgex** [comment]
PR Updated. I added a new block for viewholder lookups between "before injection" and "injection" blocks.

**Pull request merged**
