### PR TITLE
Update Kotlin example

### PR DESCRIPTION
**Pull request by WonderCsabo**
The manifest file is now found automatically, configuring it by hand
may cause issues.

### CODE REVIEW

**Comment by dodgex** [comment]
Thank you, could you also update the versions in the other samples? To have them in sync.

**Comment by WonderCsabo** [comment]
https://github.com/androidannotations/androidannotations/issues/2028#issuecomment-318151146

Maybe because of this, we should not remove the kapt block from the example, because it fixes flavors with the stable Android Gradle plugin at least.

**Comment by dodgex** [comment]
Maybe we should try to enhance the manifest finder to support the new(?) behaviour of `kapt` if the do not "fix" the [issue](https://youtrack.jetbrains.com/issue/KT-19245) you opened at kotlin.

I have an idea that could work, if i correctly understand the problem with the directories. I'll see if i get a hand on it this evening or tomorrow.

**Comment by WonderCsabo** [comment]
@dodgex thanks!

**Comment by dodgex** [comment]
[PR is up](https://github.com/androidannotations/androidannotations/pull/2030)

**Comment by WonderCsabo** [comment]
@dodgex updated.

**Comment by dodgex** [comment]
There is a travis issue due to the upgrade to 26 build tools. :/

**Comment by WonderCsabo** [comment]
@dodgex build fixed.

**Pull request merged**
