### PR TITLE
Support R2 class for resource values

### PR DESCRIPTION
**Pull request by WonderCsabo**
This PR adds support to ButterKnife R2 generator plugin. Please note only the SNAPSHOT version of that plugin generates all types of resources. For rationale, see the commit message.

### CODE REVIEW

**Comment by dodgex** [comment]
Hey Csaba, thank you for the PR. I got 2 questions.

1) What is the purpose of the R2 class? what is the advantage over R?
2) (maybe already part of the answer to 1 but:) do we always want to use R2 if it is present?

**Comment by WonderCsabo** [comment]
Hey, 

I tried to explain it in the commit message, but maybe it was not clear, sorry. 

1. The problem is with R class is that in case of library projects, the R.*.* fields are not final, so we cannot use them in annotation parameters. For the same reason, we also cannot read them for validation. To work around this, we added the `resName` parameter everywhere, which accepts a String. But that is inconvenient to use, you can have mistakes, there is no code completion etc. The R2 class has final fields, so it can be used in annotation parameters. But to actually make it work, we also have to read the values for validation, and we can only do that from the final R2 fields. This is what this PR does. 

2.Yes, maybe we should only the this if enabled by some option. I can put this behind an option flag.

**Comment by dodgex** [comment]
Thank you for explaining it again. I did not look at the commit message, so i missed the explaination there.

~~But I'm a bit confused... We already have `@ViewById(R.id.myTextView)` so I'm not sure what the problem is with R and annotation parameters...~~ 

Okay, ignore that... reading your explaination a second time revels `in case of library projects`.

Maybe it is enough to put this behind the [library](https://github.com/androidannotations/androidannotations/wiki/CustomizeAnnotationProcessing#library) option?

**Comment by WonderCsabo** [comment]
@dodgex i think we should put this behind a new flag.

**Comment by WonderCsabo** [comment]
@dodgex updated.

**Comment by dodgex** [comment]
looks fine.

**Comment by WonderCsabo** [comment]
@dodgex documentation in my fork:
https://github.com/WonderCsabo/androidannotations/wiki/Library-projects#using-r2-class
https://github.com/WonderCsabo/androidannotations/wiki/CustomizeAnnotationProcessing#user2

**Comment by dodgex** [comment]
looks good

**Comment by WonderCsabo** [comment]
I merged the doc.

**Comment by LuigiPapino** [comment]
This just saved me a lot of time. And will be very useful for instant apps.
It's working fine for me on a quiet complex project, with three layers (installedapp-> base -> sharedui).

**Pull request merged**
