### PR TITLE
Fix Kotlin example

### PR DESCRIPTION
**Pull request by WonderCsabo**

### CODE REVIEW

**Comment by dodgex** [comment]
Can you add a note about this trick to the Kotlin Wiki Page? :)

**Comment by WonderCsabo** [comment]
Yep!

**Comment by WonderCsabo** [comment]
@dodgex i extended our [Kotlin page](https://github.com/androidannotations/androidannotations/wiki/Kotlin-support).

**Comment by dodgex** [comment]
You renamed the file, this means that the wiki urls in the javadoc and sample are broken now, or am i mistaken?

**Comment by WonderCsabo** [comment]
You are right! Sorry, i will rename it back.

**Comment by dodgex** [comment]
Or you update the links. If you prefer Kotlin-support as page name

**Pull request merged**
